export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RAILWAY_API_ERROR = 'RAILWAY_API_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  RUNTIME_NOT_FOUND = 'RUNTIME_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
